name: cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.11.9
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - pip:
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - huggingface-hub==0.23.4
      - transformers==4.37.0
      - accelerate==0.23.0
      - sentencepiece==0.2.0
      - protobuf==5.27.2
      - bitsandbytes==0.43.1
      - numpy==1.26.4
